name: docker-image

on:
  push:
  schedule:
    - cron: '0 0 1 * *'  # run once-a-month

jobs:
  docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Pull finmag Docker image
      run: docker pull finmag/finmag:latest

    - name: Run simple command in finmag Docker container
      run: docker run finmag/finmag:latest bash -c "python -c \"import finmag\""

    - name: Pull dependencies Docker image
      run: docker pull finmag/finmag:dependencies

    - name: Run simple command in dependencies Docker container
      run: docker run finmag/finmag:dependencies bash -c "python -c \"import dolfin\""
