name: workflow

on:
  push:
  schedule:
    - cron: '0 0 1 * *'  # run once-a-month

jobs:
  workflow:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Initialisation
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build --no-cache -f install/docker/travis/Dockerfile -t dockertestimage .

    - name: Create docker container
      run: docker run -ti -d --name testcontainer dockertestimage

    - name: Run tests
      run: docker exec testcontainer make test-all

    # - name: Stop and remove Docker container
    #   run: |
    #     docker stop testcontainer
    # 	docker rm testcontainer
